wandb_log_name: example_project

num_classes: 10
dataset:
  dataset_name: cifar10
  root: /data/wangzili
  img_size: [ 224,224 ]

model:
  model_name: resnet50
  num_classes: ${num_classes}
loss:
  loss_name: crossentropy

optimizer:
  optimizer_name: adamw
  lr: 0.001
  weight_decay: 0.00001

iter_scheduler:
  scheduler_name: linearlr
  start_factor: 0.001
  total_iters: 1600

epoch_scheduler:
  scheduler_name: multisteplr
  milestones: [ 16,20 ]
  gamma: 0.5

metric:
  metric_name: accuracy
  topk: [ 1,5 ]

saver:
  save_interval: 10
  higher_is_better: True
  monitor: accuracy@top1
  save_dir: /data/wangzili/runs